name: CI/CD Pipeline

# D4: Triggers on push to main and any Pull Request
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  # D4a: Linting job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install linters
        run: pip install ruff black
      - name: Run linters
        run: |
          ruff check .
          black --check .

  # D4b: Testing job
  test:
    runs-on: ubuntu-latest
    needs: lint # Runs after linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install ultralytics pytest pytest-cov httpx
      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        # We check coverage for 'app.py' (module name 'app')
        run: pytest -v --maxfail=1 --disable-warnings --cov=app --cov-fail-under=60
      - name: Debug test environment
        run: |
          echo "Listing project files for verification..."
          ls -R
          echo "Checking Python version and installed packages..."
          python --version
          pip list

  # D8: Security scan job
  scan:
    runs-on: ubuntu-latest
    needs: test # Runs after testing
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install latest pip-audit
        run: pip install --upgrade pip-audit
      - name: Upgrade pip and setuptools (security fix)
        run: |
          pip install --upgrade pip setuptools
      - name: Scan dependencies for vulnerabilities
        run: |
          pip-audit --progress-spinner off --format columns || true

  # D4c: Build and push Docker image
  build-docker:
    runs-on: ubuntu-latest
    needs: scan # Runs after scanning
    permissions:
      contents: read
      packages: write # Permission to push to GHCR
    steps:
      # Free up disk space before building (critical for large builds)
      - name: Free up disk space
        run: |
          echo "Cleaning up large preinstalled SDKs and Docker cache..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          docker system prune -af || true
          df -h

      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & push Docker image (lowercase tag)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/alina1114/foodalyze:${{ github.sha }}

  # D4d: Canary deployment job
  canary-deploy:
    runs-on: ubuntu-latest
    needs: build-docker # Runs after the image is built
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull the new image
        run: docker pull ghcr.io/alina1114/foodalyze:${{ github.sha }}
      - name: Run the canary container
        run: |
          docker run \
            -d \
            --name canary \
            -p 8000:8000 \
            -e CANARY=true \
            ghcr.io/alina1114/foodalyze:${{ github.sha }}
      - name: Wait for canary to be healthy
        run: |
          echo "Waiting for canary API to start..."
          sleep 15 # Give the container 15s to start up
          # Ping the /health endpoint. -f makes it fail if status is not 200
          curl -f http://localhost:8000/health

   # D4e: Acceptance testing job
  acceptance-tests:
    runs-on: ubuntu-latest
    needs: canary-deploy # Runs after the canary is deployed
    steps:
      - name: Checkout code
        # Needed for sample image
        uses: actions/checkout@v4

      - name: Run 5+ acceptance tests
        env:
          BASE_URL: "http://16.16.192.156:8000"   # <-- Replace with your EC2 IP
        run: |
          echo "Running acceptance tests against $BASE_URL"

          # Wait up to 30s for API to become ready
          for i in {1..6}; do
            echo "Checking if API is up (attempt $i)..."
            if curl -f "$BASE_URL/health" > /dev/null 2>&1; then
              echo "API is up!"
              break
            fi
            echo "Still waiting..."
            sleep 5
          done

          echo "Test 1: /health"
          curl -f "$BASE_URL/health"

          echo "Test 2: /predict"
          curl -f -X 'POST' \
            "$BASE_URL/predict" \
            -H 'accept: application/json' \
            -H 'Content-Type: multipart/form-data' \
            -F 'file=@./tests/sample_food.jpg'

          echo "Test 3: /predict?conf=0.1"
          curl -f -X 'POST' \
            "$BASE_URL/predict?conf=0.1" \
            -H 'accept: application/json' \
            -H 'Content-Type: multipart/form-data' \
            -F 'file=@./tests/sample_food.jpg'

          echo "Test 4: /predict?conf=0.9"
          curl -f -X 'POST' \
            "$BASE_URL/predict?conf=0.9" \
            -H 'accept: application/json' \
            -H 'Content-Type: multipart/form-data' \
            -F 'file=@./tests/sample_food.jpg'

          echo "Test 5: /model_info"
          curl -f "$BASE_URL/model_info"

          echo "Test 6: / (root)"
          curl -f "$BASE_URL/"

          echo "All 6 acceptance tests passed successfully!"
